import type { StudyFolderIconName } from '../../../../shared/contracts/study'

export interface FolderIconOption {
  value: StudyFolderIconName
  label: string
}

export const FOLDER_ICON_OPTIONS = [
  { value: 'folder', label: 'Папка' },
  { value: 'book', label: 'Книга' },
  { value: 'graduation', label: 'Учёба' },
  { value: 'science', label: 'Наука' },
  { value: 'calculator', label: 'Математика' },
  { value: 'code', label: 'Программирование' },
  { value: 'languages', label: 'Языки' },
  { value: 'history', label: 'История' },
  { value: 'microscope', label: 'Исследование' },
  { value: 'art', label: 'Искусство' },
  { value: 'music', label: 'Музыка' },
  { value: 'work', label: 'Работа' },
  { value: 'archive', label: 'Архив' },
  { value: 'physics', label: 'Физика' },
  { value: 'brain', label: 'Мышление' },
  { value: 'organization', label: 'Организация' },
  { value: 'photography', label: 'Фотография' },
  { value: 'finance', label: 'Финансы' },
  { value: 'biology', label: 'Биология' },
  { value: 'geography', label: 'География' },
  { value: 'medicine', label: 'Медицина' },
  { value: 'ideas', label: 'Идеи' },
  { value: 'travel', label: 'Путешествия' },
  { value: 'notes', label: 'Заметки' },
  { value: 'design', label: 'Дизайн' },
  { value: 'projects', label: 'Проекты' },
  { value: 'law', label: 'Право' },
  { value: 'favorites', label: 'Избранное' },
  { value: 'goals', label: 'Цели' },
  { value: 'reminders', label: 'Напоминания' },
  { value: 'bookmarks', label: 'Закладки' },
  { value: 'resources', label: 'Ресурсы' },
  { value: 'calendar', label: 'Календарь' },
  { value: 'cloud', label: 'Облако' },
  { value: 'direction', label: 'Направления' },
  { value: 'database', label: 'База данных' },
  { value: 'games', label: 'Игры' },
  { value: 'home', label: 'Дом' },
  { value: 'mail', label: 'Почта' },
  { value: 'network', label: 'Сеть' },
  { value: 'security', label: 'Безопасность' },
  { value: 'shopping', label: 'Покупки' },
  { value: 'achievements', label: 'Достижения' },
  { value: 'checklist', label: 'Задачи' },
  { value: 'personal', label: 'Личное' },
  { value: 'documents', label: 'Документы' },
  { value: 'downloads', label: 'Загрузки' },
  { value: 'team', label: 'Команда' },
  { value: 'weather', label: 'Погода' },
  { value: 'sport', label: 'Спорт' }
] as const satisfies readonly FolderIconOption[]
