// Initial mobile schema from desktop migrations through 0044_workout_default_exercises.
// Generated with scripts/build-mobile-schema.mjs; preserve V1 after release.
export const mobileSchemaV1: readonly string[] = [
  "CREATE TABLE `calendar_event_occurrences` (\n  `id` text PRIMARY KEY NOT NULL,\n  `event_id` text NOT NULL,\n  `occurrence_date` text NOT NULL,\n  `note` text DEFAULT '' NOT NULL,\n  `hidden` integer DEFAULT false NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL,\n  FOREIGN KEY (`event_id`) REFERENCES `calendar_events`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  'CREATE TABLE `calendar_event_reminders` (\n  `id` text PRIMARY KEY NOT NULL,\n  `event_id` text NOT NULL,\n  `offset_minutes` integer NOT NULL,\n  `created_at` integer NOT NULL,\n  FOREIGN KEY (`event_id`) REFERENCES `calendar_events`(`id`) ON UPDATE no action ON DELETE cascade\n)',
  'CREATE TABLE `calendar_events` (\n  `id` text PRIMARY KEY NOT NULL,\n  `title` text NOT NULL,\n  `kind` text NOT NULL,\n  `event_date` text NOT NULL,\n  `event_time` text,\n  `start_date` text,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL\n)',
  'CREATE TABLE "calendar_reminder_deliveries" (\n  `id` text PRIMARY KEY NOT NULL,\n  `reminder_id` text NOT NULL,\n  `event_id` text NOT NULL,\n  `occurrence_date` text NOT NULL,\n  `title` text NOT NULL,\n  `event_time` text,\n  `offset_minutes` integer NOT NULL,\n  `delivered_at` integer NOT NULL,\n  `acknowledged_at` integer\n)',
  "CREATE TABLE `diaries` (\n  `id` text PRIMARY KEY NOT NULL,\n  `title` text NOT NULL,\n  `icon` text NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL\n, `paper_pattern` text DEFAULT 'ruled' NOT NULL, `paper_tone` text DEFAULT 'natural' NOT NULL, `cover_tone` text DEFAULT 'walnut' NOT NULL)",
  'CREATE TABLE `diary_days` (\n  `id` text PRIMARY KEY NOT NULL,\n  `diary_id` text NOT NULL,\n  `day_key` text NOT NULL,\n  `mood` text,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL,\n  FOREIGN KEY (`diary_id`) REFERENCES `diaries`(`id`) ON UPDATE no action ON DELETE cascade\n)',
  'CREATE TABLE `diary_entries` (\n  `id` text PRIMARY KEY NOT NULL,\n  `diary_day_id` text NOT NULL,\n  `text` text NOT NULL,\n  `occurred_at` integer NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL,\n  FOREIGN KEY (`diary_day_id`) REFERENCES `diary_days`(`id`) ON UPDATE no action ON DELETE cascade\n)',
  'CREATE TABLE `habit_entries` (\n  `id` text PRIMARY KEY NOT NULL,\n  `habit_id` text NOT NULL,\n  `date` text NOT NULL,\n  `value` integer DEFAULT 0 NOT NULL,\n  `skipped` integer DEFAULT false NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL,\n  FOREIGN KEY (`habit_id`) REFERENCES `habits`(`id`) ON UPDATE no action ON DELETE cascade\n)',
  "CREATE TABLE `habit_groups` (\n  `id` text PRIMARY KEY NOT NULL,\n  `name` text NOT NULL,\n  `icon` text DEFAULT 'folder' NOT NULL,\n  `color` text DEFAULT 'violet' NOT NULL,\n  `position` integer DEFAULT 0 NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL\n)",
  'CREATE TABLE `habit_reminder_deliveries` (\n  `id` text PRIMARY KEY NOT NULL,\n  `habit_id` text NOT NULL,\n  `occurrence_date` text NOT NULL,\n  `unit` integer NOT NULL,\n  `preferred_time` text NOT NULL,\n  `delivered_at` integer NOT NULL, `acknowledged_at` integer,\n  FOREIGN KEY (`habit_id`) REFERENCES `habits`(`id`) ON UPDATE no action ON DELETE cascade\n)',
  "CREATE TABLE `habits` (\n  `id` text PRIMARY KEY NOT NULL,\n  `title` text NOT NULL,\n  `group_id` text,\n  `tracking_type` text DEFAULT 'check' NOT NULL,\n  `target_value` integer DEFAULT 1 NOT NULL,\n  `unit` text DEFAULT '' NOT NULL,\n  `repeat_every_days` integer DEFAULT 1 NOT NULL,\n  `preferred_time` text,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL, `reminders_enabled` integer DEFAULT false NOT NULL, `weekdays` text DEFAULT '[]' NOT NULL,\n  FOREIGN KEY (`group_id`) REFERENCES `habit_groups`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE \"movies\" (\n  `id` text PRIMARY KEY NOT NULL,\n  `title` text NOT NULL,\n  `original_title` text,\n  `year` integer,\n  `poster_url` text,\n  `director` text DEFAULT '' NOT NULL,\n  `runtime_minutes` integer,\n  `genres_json` text DEFAULT '[]' NOT NULL,\n  `actors_json` text DEFAULT '[]' NOT NULL,\n  `description` text DEFAULT '' NOT NULL,\n  `status` text DEFAULT 'watchlist' NOT NULL,\n  `favorite` integer DEFAULT false NOT NULL,\n  `rating` integer,\n  `comments` text DEFAULT '' NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL\n, `type` text DEFAULT 'movie' NOT NULL, `season_count` integer, `episodes_per_season` integer, `episode_runtime_minutes` integer)",
  "CREATE TABLE `music_items` (\n  `id` text PRIMARY KEY NOT NULL,\n  `title` text NOT NULL,\n  `type` text DEFAULT 'track' NOT NULL,\n  `year` integer,\n  `cover_url` text,\n  `artists_json` text DEFAULT '[]' NOT NULL,\n  `album` text DEFAULT '' NOT NULL,\n  `duration_seconds` integer,\n  `track_count` integer,\n  `genres_json` text DEFAULT '[]' NOT NULL,\n  `description` text DEFAULT '' NOT NULL,\n  `status` text DEFAULT 'want_to_listen' NOT NULL,\n  `favorite` integer DEFAULT false NOT NULL,\n  `rating` integer,\n  `comments` text DEFAULT '' NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL\n)",
  'CREATE TABLE `music_playlist_items` (\n  `playlist_id` text NOT NULL,\n  `music_item_id` text NOT NULL,\n  `created_at` integer NOT NULL,\n  PRIMARY KEY(`playlist_id`, `music_item_id`),\n  FOREIGN KEY (`playlist_id`) REFERENCES `music_playlists`(`id`) ON UPDATE no action ON DELETE cascade,\n  FOREIGN KEY (`music_item_id`) REFERENCES `music_items`(`id`) ON UPDATE no action ON DELETE cascade\n)',
  'CREATE TABLE `music_playlists` (\n  `id` text PRIMARY KEY NOT NULL,\n  `name` text NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL\n, `cover_url` text)',
  "CREATE TABLE `task_groups` (\n  `id` text PRIMARY KEY NOT NULL,\n  `name` text NOT NULL,\n  `icon` text DEFAULT 'folder' NOT NULL,\n  `color` text DEFAULT 'violet' NOT NULL,\n  `position` integer DEFAULT 0 NOT NULL,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL\n)",
  "CREATE TABLE `tasks` (\n  `id` text PRIMARY KEY NOT NULL,\n  `title` text NOT NULL,\n  `description` text DEFAULT '' NOT NULL,\n  `group_id` text,\n  `status` text DEFAULT 'active' NOT NULL,\n  `priority` text DEFAULT 'normal' NOT NULL,\n  `due_date` text,\n  `due_time` text,\n  `completed_at` integer,\n  `created_at` integer NOT NULL,\n  `updated_at` integer NOT NULL,\n  FOREIGN KEY (`group_id`) REFERENCES `task_groups`(`id`) ON UPDATE no action ON DELETE set null\n)",
  'CREATE INDEX `calendar_deliveries_acknowledged_idx` ON `calendar_reminder_deliveries` (`acknowledged_at`)',
  'CREATE INDEX `calendar_deliveries_delivered_idx` ON `calendar_reminder_deliveries` (`delivered_at`)',
  'CREATE UNIQUE INDEX `calendar_deliveries_reminder_date_unique` ON `calendar_reminder_deliveries` (`reminder_id`,`occurrence_date`)',
  'CREATE INDEX `calendar_events_kind_date_idx` ON `calendar_events` (`kind`,`event_date`)',
  'CREATE INDEX `calendar_events_updated_idx` ON `calendar_events` (`updated_at`)',
  'CREATE INDEX `calendar_occurrences_date_idx` ON `calendar_event_occurrences` (`occurrence_date`)',
  'CREATE UNIQUE INDEX `calendar_occurrences_event_date_unique` ON `calendar_event_occurrences` (`event_id`,`occurrence_date`)',
  'CREATE INDEX `calendar_reminders_event_idx` ON `calendar_event_reminders` (`event_id`)',
  'CREATE UNIQUE INDEX `calendar_reminders_event_offset_unique` ON `calendar_event_reminders` (`event_id`,`offset_minutes`)',
  'CREATE INDEX `diaries_updated_idx` ON `diaries` (`updated_at`)',
  'CREATE INDEX `diary_days_diary_day_idx` ON `diary_days` (`diary_id`,`day_key`)',
  'CREATE UNIQUE INDEX `diary_days_diary_day_uq` ON `diary_days` (`diary_id`,`day_key`)',
  'CREATE INDEX `diary_days_diary_updated_idx` ON `diary_days` (`diary_id`,`updated_at`)',
  'CREATE INDEX `diary_entries_day_time_idx` ON `diary_entries` (`diary_day_id`,`occurred_at`)',
  'CREATE INDEX `diary_entries_updated_idx` ON `diary_entries` (`updated_at`)',
  'CREATE INDEX `habit_entries_date_idx` ON `habit_entries` (`date`)',
  'CREATE UNIQUE INDEX `habit_entries_habit_date_unique` ON `habit_entries` (`habit_id`,`date`)',
  'CREATE INDEX `habit_entries_habit_idx` ON `habit_entries` (`habit_id`)',
  'CREATE INDEX `habit_groups_name_idx` ON `habit_groups` (`name`)',
  'CREATE INDEX `habit_groups_position_idx` ON `habit_groups` (`position`,`created_at`)',
  'CREATE INDEX `habit_reminder_deliveries_acknowledged_idx` ON `habit_reminder_deliveries` (`acknowledged_at`)',
  'CREATE INDEX `habit_reminder_deliveries_delivered_idx` ON `habit_reminder_deliveries` (`delivered_at`)',
  'CREATE UNIQUE INDEX `habit_reminder_deliveries_habit_date_unit_unique` ON `habit_reminder_deliveries` (`habit_id`,`occurrence_date`,`unit`,`preferred_time`)',
  'CREATE INDEX `habits_group_updated_idx` ON `habits` (`group_id`,`updated_at`)',
  'CREATE INDEX `habits_updated_idx` ON `habits` (`updated_at`)',
  'CREATE INDEX `movies_favorite_updated_idx` ON `movies` (`favorite`,`updated_at`)',
  'CREATE INDEX `movies_status_updated_idx` ON `movies` (`status`,`updated_at`)',
  'CREATE INDEX `movies_title_idx` ON `movies` (`title`)',
  'CREATE INDEX `music_items_favorite_updated_idx` ON `music_items` (`favorite`,`updated_at`)',
  'CREATE INDEX `music_items_status_updated_idx` ON `music_items` (`status`,`updated_at`)',
  'CREATE INDEX `music_items_title_idx` ON `music_items` (`title`)',
  'CREATE INDEX `music_playlist_items_music_item_idx` ON `music_playlist_items` (`music_item_id`)',
  'CREATE INDEX `music_playlists_name_idx` ON `music_playlists` (`name`)',
  'CREATE INDEX `music_playlists_updated_idx` ON `music_playlists` (`updated_at`)',
  'CREATE INDEX `task_groups_name_idx` ON `task_groups` (`name`)',
  'CREATE INDEX `task_groups_position_idx` ON `task_groups` (`position`,`created_at`)',
  'CREATE INDEX `tasks_due_date_idx` ON `tasks` (`due_date`)',
  'CREATE INDEX `tasks_group_status_idx` ON `tasks` (`group_id`,`status`)',
  'CREATE INDEX `tasks_status_due_idx` ON `tasks` (`status`,`due_date`)',
  'CREATE INDEX `tasks_updated_idx` ON `tasks` (`updated_at`)'
]
